### ISSUE TITLE
When enabling softdelete, make sure it's filtered correctly

### ISSUE THREAD

**Issue by steffendsommer** [nodes-vapor/sugar#11]
When opting in to soft-delete, every query on the model should be filtering out softdeletes.

**Comment by BrettRToomey** [comment]
Done.

**Comment by steffendsommer** [comment]
Re-opening since it got reverted (https://github.com/nodes-vapor/sugar/pull/14) - let's see if we can come up with another strategy of it we should wait for Vapor to implement this.

**Comment by steffendsommer** [comment]
Closing since it's in Vapor 2.
