### ISSUE TITLE
Date().endOfWeek() seems to be broken

### ISSUE THREAD

**Issue by Casperhr** [nodes-vapor/sugar#36]
let a = Date() //2017-06-26 00:00:00

a.endOfWeek() // 2017-06-25 00:00:00

**Comment by kimdv** [comment]
The calendars first weekday is sunday. So it will take you a day back because the next sunday isn't the next sunday. Hope you understand 😅 

But try something like this 

```
public func endOfWeek(calendar: Calendar = Calendar(identifier: .gregorian)) -> Date {
        var cal = calendar
        cal.firstWeekday = Weekday.monday.rawValue
        
        var components = cal.dateComponents([.yearForWeekOfYear, .weekOfYear], from: self.endOfDay())
        components.weekday = Weekday.sunday.rawValue
        
        let startOfWeek = cal.date(from: components)!
        return startOfWeek.endOfDay()
    }
```


I could also make a pull request @Casperhr 😄

**Comment by Casperhr** [comment]
@kimdv that would be lovely! thanks a lot

**Comment by kimdv** [comment]
Made a pull request 10 min ago 👍
